import { StyleSheet } from "react-native";

export const RecipeStyles = StyleSheet.create({
  safe: { backgroundColor: "white" },
  headerImageWrap: { position: "relative" },
  headerImage: { width: "100%", borderRadius: 10 },
  headerOverlay: {
    position: "absolute",
    top: 12,
    left: 12,
    right: 12,
    bottom: 12,
  },
  headerTextBlock: { gap: 12 },
  searchInputWrapper: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    marginBottom: 40,
    marginTop: 12,
    backgroundColor: "white",
    borderRadius: 10,
  },
  searchInputWithIcon: {
    flex: 1,
  },
  searchInputIcon: {
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
    marginRight: 14,
  },
  listWrap: {
    marginTop: -25,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: "white",
  },
  list: { paddingTop: 15 },
  listContent: { paddingBottom: 24, flexGrow: 1 },
  listHeader: { marginBottom: 16 },
  countText: {
    color: "rgba(136, 148, 162, 1)",
    borderWidth: 0.5,
    borderColor: "rgba(180, 194, 211, 1)",
    borderRadius: 12,
    padding: 10,
    alignSelf: "flex-start",
  },
  columnWrapper: { gap: 15, marginBottom: 20 },
  card: {
    padding: 15,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    gap: 15,
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: "rgba(180, 194, 211, 0.2)",
    backgroundColor: "white",
  },
  cardImage: { width: 48, height: 48, borderRadius: 10 },
  cardTitle: { flex: 1, flexShrink: 1 },
  heartBadge: {
    position: "absolute",
    right: 8,
    bottom: 8,
    width: 21,
    height: 21,
    justifyContent: "center",
    alignItems: "center",
  },
  /** Иконка сердца в карточке списка: поверх контента, правый нижний угол */
  cardHeartBadge: {
    position: "absolute",
    right: 8,
    bottom: 8,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "rgba(242, 244, 247, 1)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
    elevation: 2,
  },
  cellShadow: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 5,
  },
  favoriteButton: {
    borderRadius: 25,
    backgroundColor: "rgba(242, 244, 247, 1)",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 16,
  },
  bigFavouriteButtonSize: {
    width: 52,
    height: 52
  },
  smallFavouriteButtonSize: {
    width: 26,
    height: 26
  },
  centered: { justifyContent: "center", alignItems: "center", gap: 12 },
  loadingText: { color: "rgba(136, 148, 162, 1)" },
  emptyWrap: { justifyContent: "center", paddingVertical: 48 },
  emptyText: { color: "rgba(136, 148, 162, 1)", textAlign: "center" as const },
});
